# Curated OddOneOut puzzle rounds.
# All data is denormalized so these can be inserted into any DB
# without needing cached Person/Title records.
#
# Add new entries to CURATED_ROUNDS and run: flask game curated

CURATED_ROUNDS = [
    # --- 2026-02-25 ---
    {
        "puzzle_date": "2026-02-25",
        "round_number": 1,
        "title_id": 27205,
        "title_name": "Inception",
        "actor_1_id": 6193,
        "actor_1_name": "Leonardo DiCaprio",
        "actor_1_profile": "/vo4fltT9zZ1kH8nhLetz8MED6jp.jpg",
        "actor_2_id": 24045,
        "actor_2_name": "Joseph Gordon-Levitt",
        "actor_2_profile": "/z2FA8js799xqtfiFjBTicFYdfk.jpg",
        "actor_3_id": 2524,
        "actor_3_name": "Tom Hardy",
        "actor_3_profile": "/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg",
        "outsider_id": 1892,
        "outsider_name": "Matt Damon",
        "outsider_profile": "/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg",
    },
    {
        "puzzle_date": "2026-02-25",
        "round_number": 2,
        "title_id": 4607,
        "title_name": "Lost",
        "actor_1_id": 19034,
        "actor_1_name": "Evangeline Lilly",
        "actor_1_profile": "/pJHX2jd7ytre3NQbF9nlyWUqxH3.jpg",
        "actor_2_id": 12646,
        "actor_2_name": "Terry O'Quinn",
        "actor_2_profile": "/kSweOGPprLe1vDvu38wJQaWIih7.jpg",
        "actor_3_id": 129101,
        "actor_3_name": "Lance Reddick",
        "actor_3_profile": "/22mVtEXZbpt0J7S0LhIhdkfRrZV.jpg",
        "outsider_id": 17859,
        "outsider_name": "Wendell Pierce",
        "outsider_profile": "/r6yKahL6Z8l9aUX5qvWxTmWl8Nm.jpg",
    },
    {
        "puzzle_date": "2026-02-25",
        "round_number": 3,
        "title_id": 361743,
        "title_name": "Top Gun: Maverick",
        "actor_1_id": 500,
        "actor_1_name": "Tom Cruise",
        "actor_1_profile": "/maf8PhSvDCdEwjEMbYfGpojR5RP.jpg",
        "actor_2_id": 996701,
        "actor_2_name": "Miles Teller",
        "actor_2_profile": "/aciu7YM8fD0BzrrA6cJ5wDKZIA6.jpg",
        "actor_3_id": 1700685,
        "actor_3_name": "Lewis Pullman",
        "actor_3_profile": "/axcp6FswcSS1YPzO43BbyXIh2B2.jpg",
        "outsider_id": 933238,
        "outsider_name": "Rebecca Ferguson",
        "outsider_profile": "/lJloTOheuQSirSLXNA3JHsrMNfH.jpg",
    },
    # --- 2026-02-26 (same puzzle repeated for launch window) ---
    {
        "puzzle_date": "2026-02-26",
        "round_number": 1,
        "title_id": 27205,
        "title_name": "Inception",
        "actor_1_id": 6193,
        "actor_1_name": "Leonardo DiCaprio",
        "actor_1_profile": "/vo4fltT9zZ1kH8nhLetz8MED6jp.jpg",
        "actor_2_id": 24045,
        "actor_2_name": "Joseph Gordon-Levitt",
        "actor_2_profile": "/z2FA8js799xqtfiFjBTicFYdfk.jpg",
        "actor_3_id": 2524,
        "actor_3_name": "Tom Hardy",
        "actor_3_profile": "/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg",
        "outsider_id": 1892,
        "outsider_name": "Matt Damon",
        "outsider_profile": "/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg",
    },
    {
        "puzzle_date": "2026-02-26",
        "round_number": 2,
        "title_id": 4607,
        "title_name": "Lost",
        "actor_1_id": 19034,
        "actor_1_name": "Evangeline Lilly",
        "actor_1_profile": "/pJHX2jd7ytre3NQbF9nlyWUqxH3.jpg",
        "actor_2_id": 12646,
        "actor_2_name": "Terry O'Quinn",
        "actor_2_profile": "/kSweOGPprLe1vDvu38wJQaWIih7.jpg",
        "actor_3_id": 129101,
        "actor_3_name": "Lance Reddick",
        "actor_3_profile": "/22mVtEXZbpt0J7S0LhIhdkfRrZV.jpg",
        "outsider_id": 17859,
        "outsider_name": "Wendell Pierce",
        "outsider_profile": "/r6yKahL6Z8l9aUX5qvWxTmWl8Nm.jpg",
    },
    {
        "puzzle_date": "2026-02-26",
        "round_number": 3,
        "title_id": 361743,
        "title_name": "Top Gun: Maverick",
        "actor_1_id": 500,
        "actor_1_name": "Tom Cruise",
        "actor_1_profile": "/maf8PhSvDCdEwjEMbYfGpojR5RP.jpg",
        "actor_2_id": 996701,
        "actor_2_name": "Miles Teller",
        "actor_2_profile": "/aciu7YM8fD0BzrrA6cJ5wDKZIA6.jpg",
        "actor_3_id": 1700685,
        "actor_3_name": "Lewis Pullman",
        "actor_3_profile": "/axcp6FswcSS1YPzO43BbyXIh2B2.jpg",
        "outsider_id": 933238,
        "outsider_name": "Rebecca Ferguson",
        "outsider_profile": "/lJloTOheuQSirSLXNA3JHsrMNfH.jpg",
    },
    # --- 2026-02-27 ---
    {
        "puzzle_date": "2026-02-27",
        "round_number": 1,
        "title_id": 27205,
        "title_name": "Inception",
        "actor_1_id": 6193,
        "actor_1_name": "Leonardo DiCaprio",
        "actor_1_profile": "/vo4fltT9zZ1kH8nhLetz8MED6jp.jpg",
        "actor_2_id": 24045,
        "actor_2_name": "Joseph Gordon-Levitt",
        "actor_2_profile": "/z2FA8js799xqtfiFjBTicFYdfk.jpg",
        "actor_3_id": 2524,
        "actor_3_name": "Tom Hardy",
        "actor_3_profile": "/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg",
        "outsider_id": 1892,
        "outsider_name": "Matt Damon",
        "outsider_profile": "/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg",
    },
    {
        "puzzle_date": "2026-02-27",
        "round_number": 2,
        "title_id": 4607,
        "title_name": "Lost",
        "actor_1_id": 19034,
        "actor_1_name": "Evangeline Lilly",
        "actor_1_profile": "/pJHX2jd7ytre3NQbF9nlyWUqxH3.jpg",
        "actor_2_id": 12646,
        "actor_2_name": "Terry O'Quinn",
        "actor_2_profile": "/kSweOGPprLe1vDvu38wJQaWIih7.jpg",
        "actor_3_id": 129101,
        "actor_3_name": "Lance Reddick",
        "actor_3_profile": "/22mVtEXZbpt0J7S0LhIhdkfRrZV.jpg",
        "outsider_id": 17859,
        "outsider_name": "Wendell Pierce",
        "outsider_profile": "/r6yKahL6Z8l9aUX5qvWxTmWl8Nm.jpg",
    },
    {
        "puzzle_date": "2026-02-27",
        "round_number": 3,
        "title_id": 361743,
        "title_name": "Top Gun: Maverick",
        "actor_1_id": 500,
        "actor_1_name": "Tom Cruise",
        "actor_1_profile": "/maf8PhSvDCdEwjEMbYfGpojR5RP.jpg",
        "actor_2_id": 996701,
        "actor_2_name": "Miles Teller",
        "actor_2_profile": "/aciu7YM8fD0BzrrA6cJ5wDKZIA6.jpg",
        "actor_3_id": 1700685,
        "actor_3_name": "Lewis Pullman",
        "actor_3_profile": "/axcp6FswcSS1YPzO43BbyXIh2B2.jpg",
        "outsider_id": 933238,
        "outsider_name": "Rebecca Ferguson",
        "outsider_profile": "/lJloTOheuQSirSLXNA3JHsrMNfH.jpg",
    },
    # --- 2026-02-28 ---
    {
        "puzzle_date": "2026-02-28",
        "round_number": 1,
        "title_id": 27205,
        "title_name": "Inception",
        "actor_1_id": 6193,
        "actor_1_name": "Leonardo DiCaprio",
        "actor_1_profile": "/vo4fltT9zZ1kH8nhLetz8MED6jp.jpg",
        "actor_2_id": 24045,
        "actor_2_name": "Joseph Gordon-Levitt",
        "actor_2_profile": "/z2FA8js799xqtfiFjBTicFYdfk.jpg",
        "actor_3_id": 2524,
        "actor_3_name": "Tom Hardy",
        "actor_3_profile": "/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg",
        "outsider_id": 1892,
        "outsider_name": "Matt Damon",
        "outsider_profile": "/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg",
    },
    {
        "puzzle_date": "2026-02-28",
        "round_number": 2,
        "title_id": 4607,
        "title_name": "Lost",
        "actor_1_id": 19034,
        "actor_1_name": "Evangeline Lilly",
        "actor_1_profile": "/pJHX2jd7ytre3NQbF9nlyWUqxH3.jpg",
        "actor_2_id": 12646,
        "actor_2_name": "Terry O'Quinn",
        "actor_2_profile": "/kSweOGPprLe1vDvu38wJQaWIih7.jpg",
        "actor_3_id": 129101,
        "actor_3_name": "Lance Reddick",
        "actor_3_profile": "/22mVtEXZbpt0J7S0LhIhdkfRrZV.jpg",
        "outsider_id": 17859,
        "outsider_name": "Wendell Pierce",
        "outsider_profile": "/r6yKahL6Z8l9aUX5qvWxTmWl8Nm.jpg",
    },
    {
        "puzzle_date": "2026-02-28",
        "round_number": 3,
        "title_id": 361743,
        "title_name": "Top Gun: Maverick",
        "actor_1_id": 500,
        "actor_1_name": "Tom Cruise",
        "actor_1_profile": "/maf8PhSvDCdEwjEMbYfGpojR5RP.jpg",
        "actor_2_id": 996701,
        "actor_2_name": "Miles Teller",
        "actor_2_profile": "/aciu7YM8fD0BzrrA6cJ5wDKZIA6.jpg",
        "actor_3_id": 1700685,
        "actor_3_name": "Lewis Pullman",
        "actor_3_profile": "/axcp6FswcSS1YPzO43BbyXIh2B2.jpg",
        "outsider_id": 933238,
        "outsider_name": "Rebecca Ferguson",
        "outsider_profile": "/lJloTOheuQSirSLXNA3JHsrMNfH.jpg",
    },
    # --- 2026-03-10 ---
    {
        "puzzle_date": "2026-03-10",
        "round_number": 1,
        "title_id": 769,
        "title_name": "Goodfellas",
        "actor_1_id": 380,
        "actor_1_name": "Robert De Niro",
        "actor_1_profile": "/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg",
        "actor_2_id": 11486,
        "actor_2_name": "Michael Imperioli",
        "actor_2_profile": "/jfoEHR6BRMg8emtujXdM3G4JHIm.jpg",
        "actor_3_id": 4517,
        "actor_3_name": "Joe Pesci",
        "actor_3_profile": "/zbAdhqbMfRXSz26TjxJvB5f2eL5.jpg",
        "outsider_id": 1037,
        "outsider_name": "Harvey Keitel",
        "outsider_profile": "/7P30hza1neYWW3r7rSQOC736K2Z.jpg",
    },
    {
        "puzzle_date": "2026-03-10",
        "round_number": 2,
        "title_id": 1621,
        "title_name": "Boardwalk Empire",
        "actor_1_id": 39390,
        "actor_1_name": "Michael Kenneth Williams",
        "actor_1_profile": "/mafEXtGlT1qYjGmZtbjo7Ep5qK3.jpg",
        "actor_2_id": 68186,
        "actor_2_name": "Dominic Chianese",
        "actor_2_profile": "/wJIybLAbVv6VEPFpZtpxRW26aq2.jpg",
        "actor_3_id": 884,
        "actor_3_name": "Steve Buscemi",
        "actor_3_profile": "/n0pZumkrcZrAPMoPq684RhYnjPV.jpg",
        "outsider_id": 4691,
        "outsider_name": "James Gandolfini",
        "outsider_profile": "/vhtsFJZcfHdeDkFBoWMDzOS6xrP.jpg",
    },
    # --- 2026-03-10 Round 3: Little Women ---
    {
        "puzzle_date": "2026-03-10",
        "round_number": 3,
        "title_id": 331482,
        "title_name": "Little Women",
        "actor_1_id": 36592,
        "actor_1_name": "Saoirse Ronan",
        "actor_1_profile": "/w88uhQ5f8CXw9pQx5HtDrDpzQ4x.jpg",
        "actor_2_id": 1373737,
        "actor_2_name": "Florence Pugh",
        "actor_2_profile": "/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg",
        "actor_3_id": 10990,
        "actor_3_name": "Emma Watson",
        "actor_3_profile": "/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg",
        "outsider_id": 5081,
        "outsider_name": "Emily Blunt",
        "outsider_profile": "/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg",
    },
    # --- Hollywood Women: March 4, 11, 18, 25 ---
    # --- Bollywood Classics: March 6, 13, 20, 27 ---
    # --- Comedy Guys: March 8, 15, 22, 29 ---
    #
    # ---- 2026-03-04: Hollywood Women ----
    {
        "puzzle_date": "2026-03-04",
        "round_number": 1,
        "title_id": 331482,
        "title_name": "Little Women",
        "actor_1_id": 36592,
        "actor_1_name": "Saoirse Ronan",
        "actor_1_profile": "/w88uhQ5f8CXw9pQx5HtDrDpzQ4x.jpg",
        "actor_2_id": 1373737,
        "actor_2_name": "Florence Pugh",
        "actor_2_profile": "/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg",
        "actor_3_id": 10990,
        "actor_3_name": "Emma Watson",
        "actor_3_profile": "/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg",
        "outsider_id": 5081,
        "outsider_name": "Emily Blunt",
        "outsider_profile": "/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg",
    },
    {
        "puzzle_date": "2026-03-04",
        "round_number": 2,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 71070,
        "actor_3_name": "Amanda Seyfried",
        "actor_3_profile": "/gtBUIpZ3dvLpOMIVORxE6sHSyZj.jpg",
        "outsider_id": 1245,
        "outsider_name": "Scarlett Johansson",
        "outsider_profile": "/mjReG6rR7NPMEIWb1T4YWtV11ty.jpg",
    },
    {
        "puzzle_date": "2026-03-04",
        "round_number": 3,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19274,
        "actor_3_name": "Seth Rogen",
        "actor_3_profile": "/nYl9bvQzaPQLzlf0wf75clLN6Hi.jpg",
        "outsider_id": 18897,
        "outsider_name": "Jason Segel",
        "outsider_profile": "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
    },
    # ---- 2026-03-06: Bollywood Classics ----
    {
        "puzzle_date": "2026-03-06",
        "round_number": 1,
        "title_id": 19404,
        "title_name": "Dilwale Dulhania Le Jayenge",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 55061,
        "actor_2_name": "Kajol",
        "actor_2_profile": "/h4m0TkDuEMCUNaPrQxMRyFb2AQ7.jpg",
        "actor_3_id": 6217,
        "actor_3_name": "Anupam Kher",
        "actor_3_profile": "/kgU5Ap1Kf9RnicB5DMcXEZqed2f.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    {
        "puzzle_date": "2026-03-06",
        "round_number": 2,
        "title_id": 11854,
        "title_name": "Kuch Kuch Hota Hai",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 35776,
        "actor_2_name": "Rani Mukerji",
        "actor_2_profile": "/6bm1lhrEgGFpOLBjvcOi3aoQmtg.jpg",
        "actor_3_id": 42802,
        "actor_3_name": "Salman Khan",
        "actor_3_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
        "outsider_id": 78749,
        "outsider_name": "Hrithik Roshan",
        "outsider_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
    },
    {
        "puzzle_date": "2026-03-06",
        "round_number": 3,
        "title_id": 10757,
        "title_name": "Kabhi Khushi Kabhie Gham",
        "actor_1_id": 35780,
        "actor_1_name": "Amitabh Bachchan",
        "actor_1_profile": "/u69PvpWqGkywSm0YjFiw77j9eqS.jpg",
        "actor_2_id": 78749,
        "actor_2_name": "Hrithik Roshan",
        "actor_2_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
        "actor_3_id": 37233,
        "actor_3_name": "Kareena Kapoor Khan",
        "actor_3_profile": "/pJZJJ93NwJq3kb3RWtaZBYVga1x.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    # ---- 2026-03-08: Comedy Guys ----
    {
        "puzzle_date": "2026-03-08",
        "round_number": 1,
        "title_id": 18785,
        "title_name": "The Hangover",
        "actor_1_id": 51329,
        "actor_1_name": "Bradley Cooper",
        "actor_1_profile": "/sQq0nft6YZmJ7EMQwPcbaxym3AL.jpg",
        "actor_2_id": 27105,
        "actor_2_name": "Ed Helms",
        "actor_2_profile": "/gPZ8tZaNQGAc3KZRIPp9rgGbEnN.jpg",
        "actor_3_id": 58225,
        "actor_3_name": "Zach Galifianakis",
        "actor_3_profile": "/ncBSLoNUufKpg7vzx1gCtjhst8i.jpg",
        "outsider_id": 4495,
        "outsider_name": "Steve Carell",
        "outsider_profile": "/cS7Cbyff6wFVfUGem497vy9LS7A.jpg",
    },
    {
        "puzzle_date": "2026-03-08",
        "round_number": 2,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19278,
        "actor_3_name": "Bill Hader",
        "actor_3_profile": "/qyT50vQ9PQIEctE1IxDTEsBKstU.jpg",
        "outsider_id": 17419,
        "outsider_name": "Bryan Cranston",
        "outsider_profile": "/7Jahy5LZX2Fo8fGJltMreAI49hC.jpg",
    },
    {
        "puzzle_date": "2026-03-08",
        "round_number": 3,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 56323,
        "actor_3_name": "Tina Fey",
        "actor_3_profile": "/yPTAi1iucXf85UpiFPtyiTSM6do.jpg",
        "outsider_id": 54693,
        "outsider_name": "Emma Stone",
        "outsider_profile": "/erYRVpgj0XfIOeHXijDBIl2hBgN.jpg",
    },
    # ---- 2026-03-11: Hollywood Women (repeat) ----
    {
        "puzzle_date": "2026-03-11",
        "round_number": 1,
        "title_id": 331482,
        "title_name": "Little Women",
        "actor_1_id": 36592,
        "actor_1_name": "Saoirse Ronan",
        "actor_1_profile": "/w88uhQ5f8CXw9pQx5HtDrDpzQ4x.jpg",
        "actor_2_id": 1373737,
        "actor_2_name": "Florence Pugh",
        "actor_2_profile": "/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg",
        "actor_3_id": 10990,
        "actor_3_name": "Emma Watson",
        "actor_3_profile": "/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg",
        "outsider_id": 5081,
        "outsider_name": "Emily Blunt",
        "outsider_profile": "/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg",
    },
    {
        "puzzle_date": "2026-03-11",
        "round_number": 2,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 71070,
        "actor_3_name": "Amanda Seyfried",
        "actor_3_profile": "/gtBUIpZ3dvLpOMIVORxE6sHSyZj.jpg",
        "outsider_id": 1245,
        "outsider_name": "Scarlett Johansson",
        "outsider_profile": "/mjReG6rR7NPMEIWb1T4YWtV11ty.jpg",
    },
    {
        "puzzle_date": "2026-03-11",
        "round_number": 3,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19274,
        "actor_3_name": "Seth Rogen",
        "actor_3_profile": "/nYl9bvQzaPQLzlf0wf75clLN6Hi.jpg",
        "outsider_id": 18897,
        "outsider_name": "Jason Segel",
        "outsider_profile": "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
    },
    # ---- 2026-03-13: Bollywood Classics (repeat) ----
    {
        "puzzle_date": "2026-03-13",
        "round_number": 1,
        "title_id": 19404,
        "title_name": "Dilwale Dulhania Le Jayenge",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 55061,
        "actor_2_name": "Kajol",
        "actor_2_profile": "/h4m0TkDuEMCUNaPrQxMRyFb2AQ7.jpg",
        "actor_3_id": 6217,
        "actor_3_name": "Anupam Kher",
        "actor_3_profile": "/kgU5Ap1Kf9RnicB5DMcXEZqed2f.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    {
        "puzzle_date": "2026-03-13",
        "round_number": 2,
        "title_id": 11854,
        "title_name": "Kuch Kuch Hota Hai",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 35776,
        "actor_2_name": "Rani Mukerji",
        "actor_2_profile": "/6bm1lhrEgGFpOLBjvcOi3aoQmtg.jpg",
        "actor_3_id": 42802,
        "actor_3_name": "Salman Khan",
        "actor_3_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
        "outsider_id": 78749,
        "outsider_name": "Hrithik Roshan",
        "outsider_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
    },
    {
        "puzzle_date": "2026-03-13",
        "round_number": 3,
        "title_id": 10757,
        "title_name": "Kabhi Khushi Kabhie Gham",
        "actor_1_id": 35780,
        "actor_1_name": "Amitabh Bachchan",
        "actor_1_profile": "/u69PvpWqGkywSm0YjFiw77j9eqS.jpg",
        "actor_2_id": 78749,
        "actor_2_name": "Hrithik Roshan",
        "actor_2_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
        "actor_3_id": 37233,
        "actor_3_name": "Kareena Kapoor Khan",
        "actor_3_profile": "/pJZJJ93NwJq3kb3RWtaZBYVga1x.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    # ---- 2026-03-15: Comedy Guys (repeat) ----
    {
        "puzzle_date": "2026-03-15",
        "round_number": 1,
        "title_id": 18785,
        "title_name": "The Hangover",
        "actor_1_id": 51329,
        "actor_1_name": "Bradley Cooper",
        "actor_1_profile": "/sQq0nft6YZmJ7EMQwPcbaxym3AL.jpg",
        "actor_2_id": 27105,
        "actor_2_name": "Ed Helms",
        "actor_2_profile": "/gPZ8tZaNQGAc3KZRIPp9rgGbEnN.jpg",
        "actor_3_id": 58225,
        "actor_3_name": "Zach Galifianakis",
        "actor_3_profile": "/ncBSLoNUufKpg7vzx1gCtjhst8i.jpg",
        "outsider_id": 4495,
        "outsider_name": "Steve Carell",
        "outsider_profile": "/cS7Cbyff6wFVfUGem497vy9LS7A.jpg",
    },
    {
        "puzzle_date": "2026-03-15",
        "round_number": 2,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19278,
        "actor_3_name": "Bill Hader",
        "actor_3_profile": "/qyT50vQ9PQIEctE1IxDTEsBKstU.jpg",
        "outsider_id": 17419,
        "outsider_name": "Bryan Cranston",
        "outsider_profile": "/7Jahy5LZX2Fo8fGJltMreAI49hC.jpg",
    },
    {
        "puzzle_date": "2026-03-15",
        "round_number": 3,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 56323,
        "actor_3_name": "Tina Fey",
        "actor_3_profile": "/yPTAi1iucXf85UpiFPtyiTSM6do.jpg",
        "outsider_id": 54693,
        "outsider_name": "Emma Stone",
        "outsider_profile": "/erYRVpgj0XfIOeHXijDBIl2hBgN.jpg",
    },
    # ---- 2026-03-18: Hollywood Women (repeat) ----
    {
        "puzzle_date": "2026-03-18",
        "round_number": 1,
        "title_id": 331482,
        "title_name": "Little Women",
        "actor_1_id": 36592,
        "actor_1_name": "Saoirse Ronan",
        "actor_1_profile": "/w88uhQ5f8CXw9pQx5HtDrDpzQ4x.jpg",
        "actor_2_id": 1373737,
        "actor_2_name": "Florence Pugh",
        "actor_2_profile": "/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg",
        "actor_3_id": 10990,
        "actor_3_name": "Emma Watson",
        "actor_3_profile": "/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg",
        "outsider_id": 5081,
        "outsider_name": "Emily Blunt",
        "outsider_profile": "/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg",
    },
    {
        "puzzle_date": "2026-03-18",
        "round_number": 2,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 71070,
        "actor_3_name": "Amanda Seyfried",
        "actor_3_profile": "/gtBUIpZ3dvLpOMIVORxE6sHSyZj.jpg",
        "outsider_id": 1245,
        "outsider_name": "Scarlett Johansson",
        "outsider_profile": "/mjReG6rR7NPMEIWb1T4YWtV11ty.jpg",
    },
    {
        "puzzle_date": "2026-03-18",
        "round_number": 3,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19274,
        "actor_3_name": "Seth Rogen",
        "actor_3_profile": "/nYl9bvQzaPQLzlf0wf75clLN6Hi.jpg",
        "outsider_id": 18897,
        "outsider_name": "Jason Segel",
        "outsider_profile": "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
    },
    # ---- 2026-03-20: Bollywood Classics (repeat) ----
    {
        "puzzle_date": "2026-03-20",
        "round_number": 1,
        "title_id": 19404,
        "title_name": "Dilwale Dulhania Le Jayenge",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 55061,
        "actor_2_name": "Kajol",
        "actor_2_profile": "/h4m0TkDuEMCUNaPrQxMRyFb2AQ7.jpg",
        "actor_3_id": 6217,
        "actor_3_name": "Anupam Kher",
        "actor_3_profile": "/kgU5Ap1Kf9RnicB5DMcXEZqed2f.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    {
        "puzzle_date": "2026-03-20",
        "round_number": 2,
        "title_id": 11854,
        "title_name": "Kuch Kuch Hota Hai",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 35776,
        "actor_2_name": "Rani Mukerji",
        "actor_2_profile": "/6bm1lhrEgGFpOLBjvcOi3aoQmtg.jpg",
        "actor_3_id": 42802,
        "actor_3_name": "Salman Khan",
        "actor_3_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
        "outsider_id": 78749,
        "outsider_name": "Hrithik Roshan",
        "outsider_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
    },
    {
        "puzzle_date": "2026-03-20",
        "round_number": 3,
        "title_id": 10757,
        "title_name": "Kabhi Khushi Kabhie Gham",
        "actor_1_id": 35780,
        "actor_1_name": "Amitabh Bachchan",
        "actor_1_profile": "/u69PvpWqGkywSm0YjFiw77j9eqS.jpg",
        "actor_2_id": 78749,
        "actor_2_name": "Hrithik Roshan",
        "actor_2_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
        "actor_3_id": 37233,
        "actor_3_name": "Kareena Kapoor Khan",
        "actor_3_profile": "/pJZJJ93NwJq3kb3RWtaZBYVga1x.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    # ---- 2026-03-22: Comedy Guys (repeat) ----
    {
        "puzzle_date": "2026-03-22",
        "round_number": 1,
        "title_id": 18785,
        "title_name": "The Hangover",
        "actor_1_id": 51329,
        "actor_1_name": "Bradley Cooper",
        "actor_1_profile": "/sQq0nft6YZmJ7EMQwPcbaxym3AL.jpg",
        "actor_2_id": 27105,
        "actor_2_name": "Ed Helms",
        "actor_2_profile": "/gPZ8tZaNQGAc3KZRIPp9rgGbEnN.jpg",
        "actor_3_id": 58225,
        "actor_3_name": "Zach Galifianakis",
        "actor_3_profile": "/ncBSLoNUufKpg7vzx1gCtjhst8i.jpg",
        "outsider_id": 4495,
        "outsider_name": "Steve Carell",
        "outsider_profile": "/cS7Cbyff6wFVfUGem497vy9LS7A.jpg",
    },
    {
        "puzzle_date": "2026-03-22",
        "round_number": 2,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19278,
        "actor_3_name": "Bill Hader",
        "actor_3_profile": "/qyT50vQ9PQIEctE1IxDTEsBKstU.jpg",
        "outsider_id": 17419,
        "outsider_name": "Bryan Cranston",
        "outsider_profile": "/7Jahy5LZX2Fo8fGJltMreAI49hC.jpg",
    },
    {
        "puzzle_date": "2026-03-22",
        "round_number": 3,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 56323,
        "actor_3_name": "Tina Fey",
        "actor_3_profile": "/yPTAi1iucXf85UpiFPtyiTSM6do.jpg",
        "outsider_id": 54693,
        "outsider_name": "Emma Stone",
        "outsider_profile": "/erYRVpgj0XfIOeHXijDBIl2hBgN.jpg",
    },
    # ---- 2026-03-25: Hollywood Women (repeat) ----
    {
        "puzzle_date": "2026-03-25",
        "round_number": 1,
        "title_id": 331482,
        "title_name": "Little Women",
        "actor_1_id": 36592,
        "actor_1_name": "Saoirse Ronan",
        "actor_1_profile": "/w88uhQ5f8CXw9pQx5HtDrDpzQ4x.jpg",
        "actor_2_id": 1373737,
        "actor_2_name": "Florence Pugh",
        "actor_2_profile": "/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg",
        "actor_3_id": 10990,
        "actor_3_name": "Emma Watson",
        "actor_3_profile": "/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg",
        "outsider_id": 5081,
        "outsider_name": "Emily Blunt",
        "outsider_profile": "/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg",
    },
    {
        "puzzle_date": "2026-03-25",
        "round_number": 2,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 71070,
        "actor_3_name": "Amanda Seyfried",
        "actor_3_profile": "/gtBUIpZ3dvLpOMIVORxE6sHSyZj.jpg",
        "outsider_id": 1245,
        "outsider_name": "Scarlett Johansson",
        "outsider_profile": "/mjReG6rR7NPMEIWb1T4YWtV11ty.jpg",
    },
    {
        "puzzle_date": "2026-03-25",
        "round_number": 3,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19274,
        "actor_3_name": "Seth Rogen",
        "actor_3_profile": "/nYl9bvQzaPQLzlf0wf75clLN6Hi.jpg",
        "outsider_id": 18897,
        "outsider_name": "Jason Segel",
        "outsider_profile": "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
    },
    # ---- 2026-03-27: Bollywood Classics (repeat) ----
    {
        "puzzle_date": "2026-03-27",
        "round_number": 1,
        "title_id": 19404,
        "title_name": "Dilwale Dulhania Le Jayenge",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 55061,
        "actor_2_name": "Kajol",
        "actor_2_profile": "/h4m0TkDuEMCUNaPrQxMRyFb2AQ7.jpg",
        "actor_3_id": 6217,
        "actor_3_name": "Anupam Kher",
        "actor_3_profile": "/kgU5Ap1Kf9RnicB5DMcXEZqed2f.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    {
        "puzzle_date": "2026-03-27",
        "round_number": 2,
        "title_id": 11854,
        "title_name": "Kuch Kuch Hota Hai",
        "actor_1_id": 35742,
        "actor_1_name": "Shah Rukh Khan",
        "actor_1_profile": "/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg",
        "actor_2_id": 35776,
        "actor_2_name": "Rani Mukerji",
        "actor_2_profile": "/6bm1lhrEgGFpOLBjvcOi3aoQmtg.jpg",
        "actor_3_id": 42802,
        "actor_3_name": "Salman Khan",
        "actor_3_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
        "outsider_id": 78749,
        "outsider_name": "Hrithik Roshan",
        "outsider_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
    },
    {
        "puzzle_date": "2026-03-27",
        "round_number": 3,
        "title_id": 10757,
        "title_name": "Kabhi Khushi Kabhie Gham",
        "actor_1_id": 35780,
        "actor_1_name": "Amitabh Bachchan",
        "actor_1_profile": "/u69PvpWqGkywSm0YjFiw77j9eqS.jpg",
        "actor_2_id": 78749,
        "actor_2_name": "Hrithik Roshan",
        "actor_2_profile": "/5O7WrWe84WDFj7td64NVsobtHf3.jpg",
        "actor_3_id": 37233,
        "actor_3_name": "Kareena Kapoor Khan",
        "actor_3_profile": "/pJZJJ93NwJq3kb3RWtaZBYVga1x.jpg",
        "outsider_id": 42802,
        "outsider_name": "Salman Khan",
        "outsider_profile": "/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg",
    },
    # ---- 2026-03-29: Comedy Guys (repeat) ----
    {
        "puzzle_date": "2026-03-29",
        "round_number": 1,
        "title_id": 18785,
        "title_name": "The Hangover",
        "actor_1_id": 51329,
        "actor_1_name": "Bradley Cooper",
        "actor_1_profile": "/sQq0nft6YZmJ7EMQwPcbaxym3AL.jpg",
        "actor_2_id": 27105,
        "actor_2_name": "Ed Helms",
        "actor_2_profile": "/gPZ8tZaNQGAc3KZRIPp9rgGbEnN.jpg",
        "actor_3_id": 58225,
        "actor_3_name": "Zach Galifianakis",
        "actor_3_profile": "/ncBSLoNUufKpg7vzx1gCtjhst8i.jpg",
        "outsider_id": 4495,
        "outsider_name": "Steve Carell",
        "outsider_profile": "/cS7Cbyff6wFVfUGem497vy9LS7A.jpg",
    },
    {
        "puzzle_date": "2026-03-29",
        "round_number": 2,
        "title_id": 8363,
        "title_name": "Superbad",
        "actor_1_id": 21007,
        "actor_1_name": "Jonah Hill",
        "actor_1_profile": "/5aE4GgJADHzN1QsS6zkzElZSEYq.jpg",
        "actor_2_id": 39995,
        "actor_2_name": "Michael Cera",
        "actor_2_profile": "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
        "actor_3_id": 19278,
        "actor_3_name": "Bill Hader",
        "actor_3_profile": "/qyT50vQ9PQIEctE1IxDTEsBKstU.jpg",
        "outsider_id": 17419,
        "outsider_name": "Bryan Cranston",
        "outsider_profile": "/7Jahy5LZX2Fo8fGJltMreAI49hC.jpg",
    },
    {
        "puzzle_date": "2026-03-29",
        "round_number": 3,
        "title_id": 10625,
        "title_name": "Mean Girls",
        "actor_1_id": 49265,
        "actor_1_name": "Lindsay Lohan",
        "actor_1_profile": "/9orbe4F0T16K8P0hWqn6vd6czMj.jpg",
        "actor_2_id": 53714,
        "actor_2_name": "Rachel McAdams",
        "actor_2_profile": "/2zyOjda95OfAAsJvuwTV0UaznPZ.jpg",
        "actor_3_id": 56323,
        "actor_3_name": "Tina Fey",
        "actor_3_profile": "/yPTAi1iucXf85UpiFPtyiTSM6do.jpg",
        "outsider_id": 54693,
        "outsider_name": "Emma Stone",
        "outsider_profile": "/erYRVpgj0XfIOeHXijDBIl2hBgN.jpg",
    },
]
